// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: irc_key_values.proto

// Protobuf Java Version: 3.25.2
package org.opensearch.indices;

public final class IRCKeyValues {
  private IRCKeyValues() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ValuesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.opensearch.indices.Values)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string index_name = 1;</code>
     * @return Whether the indexName field is set.
     */
    boolean hasIndexName();
    /**
     * <code>required string index_name = 1;</code>
     * @return The indexName.
     */
    java.lang.String getIndexName();
    /**
     * <code>required string index_name = 1;</code>
     * @return The bytes for indexName.
     */
    com.google.protobuf.ByteString
        getIndexNameBytes();

    /**
     * <code>required string index_uuid = 2;</code>
     * @return Whether the indexUuid field is set.
     */
    boolean hasIndexUuid();
    /**
     * <code>required string index_uuid = 2;</code>
     * @return The indexUuid.
     */
    java.lang.String getIndexUuid();
    /**
     * <code>required string index_uuid = 2;</code>
     * @return The bytes for indexUuid.
     */
    com.google.protobuf.ByteString
        getIndexUuidBytes();

    /**
     * <code>required int32 shard_id = 3;</code>
     * @return Whether the shardId field is set.
     */
    boolean hasShardId();
    /**
     * <code>required int32 shard_id = 3;</code>
     * @return The shardId.
     */
    int getShardId();

    /**
     * <code>required string reader_cache_key_id = 4;</code>
     * @return Whether the readerCacheKeyId field is set.
     */
    boolean hasReaderCacheKeyId();
    /**
     * <code>required string reader_cache_key_id = 4;</code>
     * @return The readerCacheKeyId.
     */
    java.lang.String getReaderCacheKeyId();
    /**
     * <code>required string reader_cache_key_id = 4;</code>
     * @return The bytes for readerCacheKeyId.
     */
    com.google.protobuf.ByteString
        getReaderCacheKeyIdBytes();

    /**
     * <code>required bytes value = 5;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 5;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code org.opensearch.indices.Values}
   */
  public static final class Values extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.opensearch.indices.Values)
      ValuesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Values.newBuilder() to construct.
    private Values(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Values() {
      indexName_ = "";
      indexUuid_ = "";
      readerCacheKeyId_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Values();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opensearch.indices.IRCKeyValues.internal_static_org_opensearch_indices_Values_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opensearch.indices.IRCKeyValues.internal_static_org_opensearch_indices_Values_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opensearch.indices.IRCKeyValues.Values.class, org.opensearch.indices.IRCKeyValues.Values.Builder.class);
    }

    private int bitField0_;
    public static final int INDEX_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object indexName_ = "";
    /**
     * <code>required string index_name = 1;</code>
     * @return Whether the indexName field is set.
     */
    @java.lang.Override
    public boolean hasIndexName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string index_name = 1;</code>
     * @return The indexName.
     */
    @java.lang.Override
    public java.lang.String getIndexName() {
      java.lang.Object ref = indexName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          indexName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string index_name = 1;</code>
     * @return The bytes for indexName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIndexNameBytes() {
      java.lang.Object ref = indexName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        indexName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEX_UUID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object indexUuid_ = "";
    /**
     * <code>required string index_uuid = 2;</code>
     * @return Whether the indexUuid field is set.
     */
    @java.lang.Override
    public boolean hasIndexUuid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string index_uuid = 2;</code>
     * @return The indexUuid.
     */
    @java.lang.Override
    public java.lang.String getIndexUuid() {
      java.lang.Object ref = indexUuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          indexUuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string index_uuid = 2;</code>
     * @return The bytes for indexUuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIndexUuidBytes() {
      java.lang.Object ref = indexUuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        indexUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHARD_ID_FIELD_NUMBER = 3;
    private int shardId_ = 0;
    /**
     * <code>required int32 shard_id = 3;</code>
     * @return Whether the shardId field is set.
     */
    @java.lang.Override
    public boolean hasShardId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int32 shard_id = 3;</code>
     * @return The shardId.
     */
    @java.lang.Override
    public int getShardId() {
      return shardId_;
    }

    public static final int READER_CACHE_KEY_ID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object readerCacheKeyId_ = "";
    /**
     * <code>required string reader_cache_key_id = 4;</code>
     * @return Whether the readerCacheKeyId field is set.
     */
    @java.lang.Override
    public boolean hasReaderCacheKeyId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string reader_cache_key_id = 4;</code>
     * @return The readerCacheKeyId.
     */
    @java.lang.Override
    public java.lang.String getReaderCacheKeyId() {
      java.lang.Object ref = readerCacheKeyId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          readerCacheKeyId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string reader_cache_key_id = 4;</code>
     * @return The bytes for readerCacheKeyId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReaderCacheKeyIdBytes() {
      java.lang.Object ref = readerCacheKeyId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readerCacheKeyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes value = 5;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required bytes value = 5;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIndexName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIndexUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasShardId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReaderCacheKeyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, indexName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, indexUuid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, shardId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, readerCacheKeyId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBytes(5, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, indexName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, indexUuid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, shardId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, readerCacheKeyId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.opensearch.indices.IRCKeyValues.Values)) {
        return super.equals(obj);
      }
      org.opensearch.indices.IRCKeyValues.Values other = (org.opensearch.indices.IRCKeyValues.Values) obj;

      if (hasIndexName() != other.hasIndexName()) return false;
      if (hasIndexName()) {
        if (!getIndexName()
            .equals(other.getIndexName())) return false;
      }
      if (hasIndexUuid() != other.hasIndexUuid()) return false;
      if (hasIndexUuid()) {
        if (!getIndexUuid()
            .equals(other.getIndexUuid())) return false;
      }
      if (hasShardId() != other.hasShardId()) return false;
      if (hasShardId()) {
        if (getShardId()
            != other.getShardId()) return false;
      }
      if (hasReaderCacheKeyId() != other.hasReaderCacheKeyId()) return false;
      if (hasReaderCacheKeyId()) {
        if (!getReaderCacheKeyId()
            .equals(other.getReaderCacheKeyId())) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIndexName()) {
        hash = (37 * hash) + INDEX_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getIndexName().hashCode();
      }
      if (hasIndexUuid()) {
        hash = (37 * hash) + INDEX_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getIndexUuid().hashCode();
      }
      if (hasShardId()) {
        hash = (37 * hash) + SHARD_ID_FIELD_NUMBER;
        hash = (53 * hash) + getShardId();
      }
      if (hasReaderCacheKeyId()) {
        hash = (37 * hash) + READER_CACHE_KEY_ID_FIELD_NUMBER;
        hash = (53 * hash) + getReaderCacheKeyId().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.opensearch.indices.IRCKeyValues.Values parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.indices.IRCKeyValues.Values parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.indices.IRCKeyValues.Values parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.indices.IRCKeyValues.Values parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.indices.IRCKeyValues.Values parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opensearch.indices.IRCKeyValues.Values parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opensearch.indices.IRCKeyValues.Values parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opensearch.indices.IRCKeyValues.Values parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.opensearch.indices.IRCKeyValues.Values parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.opensearch.indices.IRCKeyValues.Values parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opensearch.indices.IRCKeyValues.Values parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opensearch.indices.IRCKeyValues.Values parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opensearch.indices.IRCKeyValues.Values prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.opensearch.indices.Values}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.opensearch.indices.Values)
        org.opensearch.indices.IRCKeyValues.ValuesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opensearch.indices.IRCKeyValues.internal_static_org_opensearch_indices_Values_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opensearch.indices.IRCKeyValues.internal_static_org_opensearch_indices_Values_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opensearch.indices.IRCKeyValues.Values.class, org.opensearch.indices.IRCKeyValues.Values.Builder.class);
      }

      // Construct using org.opensearch.indices.IRCKeyValues.Values.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        indexName_ = "";
        indexUuid_ = "";
        shardId_ = 0;
        readerCacheKeyId_ = "";
        value_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opensearch.indices.IRCKeyValues.internal_static_org_opensearch_indices_Values_descriptor;
      }

      @java.lang.Override
      public org.opensearch.indices.IRCKeyValues.Values getDefaultInstanceForType() {
        return org.opensearch.indices.IRCKeyValues.Values.getDefaultInstance();
      }

      @java.lang.Override
      public org.opensearch.indices.IRCKeyValues.Values build() {
        org.opensearch.indices.IRCKeyValues.Values result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.opensearch.indices.IRCKeyValues.Values buildPartial() {
        org.opensearch.indices.IRCKeyValues.Values result = new org.opensearch.indices.IRCKeyValues.Values(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.opensearch.indices.IRCKeyValues.Values result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.indexName_ = indexName_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.indexUuid_ = indexUuid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.shardId_ = shardId_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.readerCacheKeyId_ = readerCacheKeyId_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opensearch.indices.IRCKeyValues.Values) {
          return mergeFrom((org.opensearch.indices.IRCKeyValues.Values)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opensearch.indices.IRCKeyValues.Values other) {
        if (other == org.opensearch.indices.IRCKeyValues.Values.getDefaultInstance()) return this;
        if (other.hasIndexName()) {
          indexName_ = other.indexName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasIndexUuid()) {
          indexUuid_ = other.indexUuid_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasShardId()) {
          setShardId(other.getShardId());
        }
        if (other.hasReaderCacheKeyId()) {
          readerCacheKeyId_ = other.readerCacheKeyId_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasIndexName()) {
          return false;
        }
        if (!hasIndexUuid()) {
          return false;
        }
        if (!hasShardId()) {
          return false;
        }
        if (!hasReaderCacheKeyId()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                indexName_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                indexUuid_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                shardId_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                readerCacheKeyId_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                value_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object indexName_ = "";
      /**
       * <code>required string index_name = 1;</code>
       * @return Whether the indexName field is set.
       */
      public boolean hasIndexName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string index_name = 1;</code>
       * @return The indexName.
       */
      public java.lang.String getIndexName() {
        java.lang.Object ref = indexName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            indexName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string index_name = 1;</code>
       * @return The bytes for indexName.
       */
      public com.google.protobuf.ByteString
          getIndexNameBytes() {
        java.lang.Object ref = indexName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          indexName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string index_name = 1;</code>
       * @param value The indexName to set.
       * @return This builder for chaining.
       */
      public Builder setIndexName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        indexName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string index_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndexName() {
        indexName_ = getDefaultInstance().getIndexName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string index_name = 1;</code>
       * @param value The bytes for indexName to set.
       * @return This builder for chaining.
       */
      public Builder setIndexNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        indexName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object indexUuid_ = "";
      /**
       * <code>required string index_uuid = 2;</code>
       * @return Whether the indexUuid field is set.
       */
      public boolean hasIndexUuid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string index_uuid = 2;</code>
       * @return The indexUuid.
       */
      public java.lang.String getIndexUuid() {
        java.lang.Object ref = indexUuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            indexUuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string index_uuid = 2;</code>
       * @return The bytes for indexUuid.
       */
      public com.google.protobuf.ByteString
          getIndexUuidBytes() {
        java.lang.Object ref = indexUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          indexUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string index_uuid = 2;</code>
       * @param value The indexUuid to set.
       * @return This builder for chaining.
       */
      public Builder setIndexUuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        indexUuid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string index_uuid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndexUuid() {
        indexUuid_ = getDefaultInstance().getIndexUuid();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string index_uuid = 2;</code>
       * @param value The bytes for indexUuid to set.
       * @return This builder for chaining.
       */
      public Builder setIndexUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        indexUuid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int shardId_ ;
      /**
       * <code>required int32 shard_id = 3;</code>
       * @return Whether the shardId field is set.
       */
      @java.lang.Override
      public boolean hasShardId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int32 shard_id = 3;</code>
       * @return The shardId.
       */
      @java.lang.Override
      public int getShardId() {
        return shardId_;
      }
      /**
       * <code>required int32 shard_id = 3;</code>
       * @param value The shardId to set.
       * @return This builder for chaining.
       */
      public Builder setShardId(int value) {

        shardId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 shard_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearShardId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        shardId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object readerCacheKeyId_ = "";
      /**
       * <code>required string reader_cache_key_id = 4;</code>
       * @return Whether the readerCacheKeyId field is set.
       */
      public boolean hasReaderCacheKeyId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string reader_cache_key_id = 4;</code>
       * @return The readerCacheKeyId.
       */
      public java.lang.String getReaderCacheKeyId() {
        java.lang.Object ref = readerCacheKeyId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            readerCacheKeyId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string reader_cache_key_id = 4;</code>
       * @return The bytes for readerCacheKeyId.
       */
      public com.google.protobuf.ByteString
          getReaderCacheKeyIdBytes() {
        java.lang.Object ref = readerCacheKeyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          readerCacheKeyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string reader_cache_key_id = 4;</code>
       * @param value The readerCacheKeyId to set.
       * @return This builder for chaining.
       */
      public Builder setReaderCacheKeyId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        readerCacheKeyId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required string reader_cache_key_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearReaderCacheKeyId() {
        readerCacheKeyId_ = getDefaultInstance().getReaderCacheKeyId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>required string reader_cache_key_id = 4;</code>
       * @param value The bytes for readerCacheKeyId to set.
       * @return This builder for chaining.
       */
      public Builder setReaderCacheKeyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        readerCacheKeyId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 5;</code>
       * @return Whether the value field is set.
       */
      @java.lang.Override
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required bytes value = 5;</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 5;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.opensearch.indices.Values)
    }

    // @@protoc_insertion_point(class_scope:org.opensearch.indices.Values)
    private static final org.opensearch.indices.IRCKeyValues.Values DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opensearch.indices.IRCKeyValues.Values();
    }

    public static org.opensearch.indices.IRCKeyValues.Values getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Values>
        PARSER = new com.google.protobuf.AbstractParser<Values>() {
      @java.lang.Override
      public Values parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Values> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Values> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.opensearch.indices.IRCKeyValues.Values getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opensearch_indices_Values_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opensearch_indices_Values_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024irc_key_values.proto\022\026org.opensearch.i" +
      "ndices\"n\n\006Values\022\022\n\nindex_name\030\001 \002(\t\022\022\n\n" +
      "index_uuid\030\002 \002(\t\022\020\n\010shard_id\030\003 \002(\005\022\033\n\023re" +
      "ader_cache_key_id\030\004 \002(\t\022\r\n\005value\030\005 \002(\014B\016" +
      "B\014IRCKeyValues"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_opensearch_indices_Values_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_opensearch_indices_Values_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opensearch_indices_Values_descriptor,
        new java.lang.String[] { "IndexName", "IndexUuid", "ShardId", "ReaderCacheKeyId", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
