name: Gradle Assemble
on: [pull_request]

jobs:
  assemble:
    if: github.repository == 'peteralfonsi/OpenSearch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
      - name: Run Gradle (assemble)
        run: |
          ./gradlew assemble --parallel --no-build-cache -PDISABLE_BUILD_CACHE
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: tiered-caching-artifact
          path: distribution/archives/linux-tar/build/distributions/opensearch-min-3.0.0-SNAPSHOT-linux-x64.tar.gz
